### PR TITLE
Fix player speed

### LINKED ISSUE #7: Player speed should be constant, the acceleration shouldn't exist

### PR DESCRIPTION
**Pull request by rafiiary**
This is just an idea I'm proposing for clamping the player speed so they don't go too fast. We can do this with different magnitudes for the different characters. The speed has been arbitrarily chosen as 5.0f for now.

### CODE REVIEW

**Comment by evank28** [comment]
#12 Should be merged first

**Review by evank28 — APPROVED** [review]

File: Assets/Scripts/MovePB.cs [hunk 1]
```diff
@@ -37,8 +39,12 @@ private void FixedUpdate()
         _userRot += new Vector3(0, _rotationInput, 0);
 
         _transform.rotation = Quaternion.Euler(_userRot);
-        _rigidbody.velocity += transform.forward * _playerInput * InputScale;
-        
+
+        // Up is always z so velocity of x and z is clamped down
```
Comment (evank28) [inline Assets/Scripts/MovePB.cs]: You mean "Up is always *y*" right?

File: Assets/Scripts/MovePB.cs [hunk 2]
```diff
@@ -37,8 +39,12 @@ private void FixedUpdate()
...
+        if (euclideanNorm(_rigidbody.velocity.x,
+                          _rigidbody.velocity.z) < MaxSpeed)
```
Comment (evank28) [inline Assets/Scripts/MovePB.cs]: As a style thing, I would use the parentheses {} for any if statement, even 1-liner. This is because, if someone adds code later, they may forget to add the {} and this would result in a bug.

**Review by evank28 — APPROVED** [review]
lgtm

File: Assets/Scripts/MovePB.cs (hunk 1 above)
Comment (rafiiary) [reply Assets/Scripts/MovePB.cs]: Oops LOL

File: Assets/Scripts/MovePB.cs (hunk 2 above)
Comment (rafiiary) [reply Assets/Scripts/MovePB.cs]: Sure
